apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '6500'
  name: autoscale-service
  labels:
    app: autoscale-demo
spec:
  type: ClusterIP
  ports:
    - name: http-autoscale
      port: 8080
      targetPort: http-autoscale
    - name: tcp-svjmx
      port: 6500
      protocol: TCP
      targetPort: 6500
  selector:
    app: autoscale-demo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-deployment
  labels:
    app: "autoscale-demo"
spec:
  selector:
    matchLabels:
      app: "autoscale-demo"
  replicas: 1
  template:
    metadata:
      labels:
        app: "autoscale-demo"
    spec:
      containers:
      - name: "autoscale-demo"
        image: "docker.io/armohan/autoscale:1.0"
        imagePullPolicy: "Always"
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: http-autoscale
            path: /ping
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: http-autoscale
            path: /ping
        ports:
        - name: http-autoscale
          containerPort: 8080
        - name: tcp-svjmx
          containerPort: 6500
